
---
- name: Test playbook for SSL error
  hosts: all
  gather_facts: no

  tasks:
    - name: Fail with SSLV3_ALERT_HANDSHAKE_FAILURE error
      uri:
        url: https://{{ hostvars['node1']['ansible_default_ipv4']['address'] }}
        validate_certs: false
      register: result
      failed_when: result.status != 200

    - name: Print SSL error message
      debug:
        msg: "{{ hostvars['node1']['ssl_error_message'] }}"
      vars:
        ssl_error_message: "<urlopen error [SSL:SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:590)>"
