
- name: Test Ansible Compiler
  hosts: localhost
  tasks:
    - name: Check for TypeError: _execute_module() got an unexpected keyword argument 'wrap_async'
      command: ./ansible test_module --wrap_async
      ignore_errors: true
      register: result
      failed_when: "result.rc not in [0, 1]"
      changed_when: false

    - name: Print result
      debug:
        var: result
