
---
- hosts: all
  become: yes
  tasks:
    - name: Loop task throwing an error
      shell: |
        for i in {1..3}
        do
          if [ $i -eq 3 ]
          then
            echo "Failing on ${i}"
            exit 1
          fi
          echo "${i} is okay"
        done
      register: result
      ignore_errors: yes

    - name: Rescue section with failed task variable
      debug:
        var: ansible_failed_task
      when: result is failed
