
- hosts: localhost
  gather_facts: no

  tasks:
  - name: exception_handling
    block:
       - debug:
           msg: 'Inside a block'
       - include_role:
           name: dummy_role
         rescue:
           - debug:
               msg: 'Caught an error inside a block'
         always:
           - debug:
               msg: 'Executed always block'
    vars:
       ansible_exit_on_errors: true
       ansible_fatal_errors: true
