
- name: Test playbook for 'Broken build CloudStackException ...' issue
  hosts: localhost
  become: true

  tasks:
    - name: Generate random IPv6 address with invalid format
      set_fact:
        ipv6_address: "{{('invalid_ipv6_address_' ~ range(10,100)|random ~ ':0000:0000:0000:0000:0000:0000:0000') | random}}"
    
    - name: Create multiple Isolated Networks with same Vlan ID and different other ids
      community.general.cloudstack_network:
        name: "{{ item }}"
        display_text: "Testing"
        physical_network_id: "{{ range(10, 100)|random }}"
        vlan: "100"
        zone: "{{ range(1,3)|random }}"
        state: present
      loop:
        - "default-1"
        - "default-2"
    
    - name: Ensure error is thrown if there are more than 1 default Isolated networks are found for account
      community.general.cloudstack_network:
        name: "default_network"
        display_text: "Testing"
        physical_network_id: "{{ range(10, 100)|random }}"
        vlan: "100"
        zone: "{{ range(1,3)|random }}"
        state: present
      register: response

    - name: Fail the playbook if no error is thrown
      fail:
        msg: "Failed to throw error"
      when: "'More than 1 default Isolated networks are found for account' not in response.stderr"
