yaml
- name: Test playbook for GitHub issue #123
  hosts: localhost
  gather_facts: no
  vars:
    my_list: [1, 2, 3]
  tasks:
    - name: Try to iterate over an integer
      debug:
        msg: "{{ item }}"
      with_items: "{{ 10 }}"
    # The following task should cause an error
    - name: Pass an integer to "copy" module
      copy:
        content: "This is a test"
        dest: "/tmp/test"
        mode: "{{ 755 }}"
        owner: "{{ 'root' if 1 else 'nobody' }}" # This will evaluate to "root"
        group: "{{ 'nogroup' | random }}" # This should generate a random string
        backup: "{{ true if 'yes' else false }}" # This will evaluate to true
        force: "{{ 10 }}" # This should cause an error
