
- name: Test error handling in run_once task
  hosts: all
  gather_facts: false

  tasks:
    - name: Run custom module with run_once
      run_once: true
      custom_module:
        arg1: value1
        arg2: value2
      register: module_result

    - name: Execute rescue block
      debug:
        msg: "Rescue block executed"
      rescue:
        - debug:
            msg: "Rescue block executed"

    - name: Execute always block
      debug:
        msg: "Always block executed"
      always:
        - debug:
            msg: "Always block executed"
