
---
- hosts: all
  gather_facts: no

  tasks:
    - name: Test Ansible error handling rescue block
      command: "echo 'Test fail' && exit 1"
      register: command_output
      ignore_errors: true

      rescue:
        - fail:
          - debug:
            msg: "Command failed with error"
